/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.20
 */

#include "sipAPIqti.h"

#line 234 "src/scripting/qti.sip"
#include "src/ScriptEdit.h"
#line 12 "../tmp/qtiplot/sipqtiScriptEdit.cpp"

#line 27 "/usr/share/sip/PyQt4/QtCore/qstring.sip"
#include <qstring.h>
#line 16 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qcolor.sip"
#include <qcolor.h>
#line 19 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 265 "/usr/share/sip/PyQt4/QtCore/qvariant.sip"
#include <qvariant.h>
#line 22 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 25 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 647 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 28 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qmimedata.sip"
#include <qmimedata.h>
#line 31 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 347 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 34 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 37 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 596 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 40 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 505 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 43 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 739 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 46 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 765 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 49 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 792 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 52 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 781 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 55 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 618 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 58 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 252 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 61 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 524 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 64 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 561 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 67 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 474 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 70 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 351 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 73 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 336 "/usr/share/sip/PyQt4/QtGui/qtextformat.sip"
#include <qtextformat.h>
#line 76 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 79 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qfont.sip"
#include <qfont.h>
#line 82 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 210 "/usr/share/sip/PyQt4/QtGui/qprinter.sip"
#include <qprinter.h>
#line 85 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qtextcursor.sip"
#include <qtextcursor.h>
#line 88 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 28 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 91 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qtextedit.sip"
#include <qtextedit.h>
#line 35 "/usr/share/sip/PyQt4/QtGui/qtextedit.sip"
#include <qtextedit.h>
#line 96 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 99 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qpoint.sip"
#include <qpoint.h>
#line 102 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qrect.sip"
#include <qrect.h>
#line 105 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qmenu.sip"
#include <qmenu.h>
#line 108 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 98 "/usr/share/sip/PyQt4/QtCore/qurl.sip"
#include <qurl.h>
#line 111 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 59 "/usr/share/sip/PyQt4/QtGui/qtextdocument.sip"
#include <qtextdocument.h>
#line 114 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qtextoption.sip"
#include <qtextoption.h>
#line 117 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qtextedit.sip"
#include <qtextedit.h>
#line 120 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qtextedit.sip"
#include <qtextedit.h>
#line 123 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 59 "/usr/share/sip/PyQt4/QtGui/qtextdocument.sip"
#include <qtextdocument.h>
#line 126 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 28 "/usr/share/sip/PyQt4/QtGui/qwidget.sip"
#include <qwidget.h>
#line 129 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 115 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 132 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qscrollbar.sip"
#include <qscrollbar.h>
#line 135 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 28 "/usr/share/sip/PyQt4/QtCore/qmargins.sip"
#include <qmargins.h>
#line 138 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qsize.sip"
#include <qsize.h>
#line 141 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qpainter.sip"
#include <qpainter.h>
#line 144 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qframe.sip"
#include <qframe.h>
#line 147 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 150 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 153 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 28 "/usr/share/sip/PyQt4/QtGui/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 156 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 28 "/usr/share/sip/PyQt4/QtGui/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 159 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qlocale.sip"
#include <qlocale.h>
#line 162 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 165 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qregion.sip"
#include <qregion.h>
#line 168 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 28 "/usr/share/sip/PyQt4/QtGui/qwidget.sip"
#include <qwidget.h>
#line 171 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 32 "/usr/share/sip/PyQt4/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 174 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 177 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 180 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 183 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qpalette.sip"
#include <qpalette.h>
#line 186 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 607 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 189 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 854 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 192 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 403 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 195 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 574 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 198 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 548 "/usr/share/sip/PyQt4/QtGui/qevent.sip"
#include <qevent.h>
#line 201 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 28 "/usr/share/sip/PyQt4/QtGui/qinputcontext.sip"
#include <qinputcontext.h>
#line 204 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 52 "/usr/share/sip/PyQt4/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 207 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 34 "/usr/share/sip/PyQt4/QtGui/qx11info_x11.sip"
#include <qx11info_x11.h>
#line 210 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 115 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 213 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qaction.sip"
#include <qaction.h>
#line 216 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qlayout.sip"
#include <qlayout.h>
#line 219 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 222 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 225 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 228 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qcursor.sip"
#include <qcursor.h>
#line 231 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qicon.sip"
#include <qicon.h>
#line 234 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 237 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtGui/qstyle.sip"
#include <qstyle.h>
#line 240 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 368 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 243 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 29 "/usr/share/sip/PyQt4/QtCore/qobject.sip"
#include <qobject.h>
#line 246 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 28 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 249 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 115 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 252 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qthread.sip"
#include <qthread.h>
#line 255 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qregexp.sip"
#include <qregexp.h>
#line 258 "../tmp/qtiplot/sipqtiScriptEdit.cpp"
#line 26 "/usr/share/sip/PyQt4/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 261 "../tmp/qtiplot/sipqtiScriptEdit.cpp"


extern "C" {static PyObject *meth_ScriptEdit_execute(PyObject *, PyObject *);}
static PyObject *meth_ScriptEdit_execute(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::ScriptEdit *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_ScriptEdit, &sipCpp))
        {
            sipCpp->execute();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ScriptEdit, sipName_execute, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_ScriptEdit_executeAll(PyObject *, PyObject *);}
static PyObject *meth_ScriptEdit_executeAll(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::ScriptEdit *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_ScriptEdit, &sipCpp))
        {
            sipCpp->executeAll();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ScriptEdit, sipName_executeAll, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_ScriptEdit_evaluate(PyObject *, PyObject *);}
static PyObject *meth_ScriptEdit_evaluate(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::ScriptEdit *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_ScriptEdit, &sipCpp))
        {
            sipCpp->evaluate();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ScriptEdit, sipName_evaluate, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_ScriptEdit_print(PyObject *, PyObject *);}
static PyObject *meth_ScriptEdit_print(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
         ::ScriptEdit *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_ScriptEdit, &sipCpp))
        {
            sipCpp->print();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ScriptEdit, sipName_print, SIP_NULLPTR);

    return SIP_NULLPTR;
}


extern "C" {static PyObject *meth_ScriptEdit_insertFunction(PyObject *, PyObject *);}
static PyObject *meth_ScriptEdit_insertFunction(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = SIP_NULLPTR;

    {
        const  ::QString* a0;
        int a0State = 0;
         ::ScriptEdit *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_ScriptEdit, &sipCpp, sipType_QString,&a0, &a0State))
        {
            sipCpp->insertFunction(*a0);
            sipReleaseType(const_cast< ::QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_ScriptEdit, sipName_insertFunction, SIP_NULLPTR);

    return SIP_NULLPTR;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_ScriptEdit(void *, const sipTypeDef *);}
static void *cast_ScriptEdit(void *sipCppV, const sipTypeDef *targetType)
{
     ::ScriptEdit *sipCpp = reinterpret_cast< ::ScriptEdit *>(sipCppV);

    if (targetType == sipType_QTextEdit)
        return static_cast< ::QTextEdit *>(sipCpp);

    if (targetType == sipType_QAbstractScrollArea)
        return static_cast< ::QAbstractScrollArea *>(sipCpp);

    if (targetType == sipType_QFrame)
        return static_cast< ::QFrame *>(sipCpp);

    if (targetType == sipType_QWidget)
        return static_cast< ::QWidget *>(sipCpp);

    if (targetType == sipType_QObject)
        return static_cast< ::QObject *>(sipCpp);

    if (targetType == sipType_QPaintDevice)
        return static_cast< ::QPaintDevice *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_ScriptEdit(void *, int);}
static void release_ScriptEdit(void *sipCppV, int)
{
     ::ScriptEdit *sipCpp = reinterpret_cast< ::ScriptEdit *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_ScriptEdit(sipSimpleWrapper *);}
static void dealloc_ScriptEdit(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_ScriptEdit(sipGetAddress(sipSelf), 0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_ScriptEdit[] = {{33, 1, 1}};


static PyMethodDef methods_ScriptEdit[] = {
    {SIP_MLNAME_CAST(sipName_evaluate), meth_ScriptEdit_evaluate, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_execute), meth_ScriptEdit_execute, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_executeAll), meth_ScriptEdit_executeAll, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_insertFunction), meth_ScriptEdit_insertFunction, METH_VARARGS, SIP_NULLPTR},
    {SIP_MLNAME_CAST(sipName_print), meth_ScriptEdit_print, METH_VARARGS, SIP_NULLPTR}
};


static pyqt4ClassPluginDef plugin_ScriptEdit = {
    & ::ScriptEdit::staticMetaObject,
    0,
    SIP_NULLPTR
};


sipClassTypeDef sipTypeDef_qti_ScriptEdit = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_ScriptEdit,
        {SIP_NULLPTR},
        &plugin_ScriptEdit
    },
    {
        sipNameNr_ScriptEdit,
        {0, 0, 1},
        5, methods_ScriptEdit,
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    SIP_NULLPTR,
    -1,
    -1,
    supers_ScriptEdit,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
#if PY_MAJOR_VERSION >= 3
    SIP_NULLPTR,
    SIP_NULLPTR,
#else
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
#endif
    dealloc_ScriptEdit,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    release_ScriptEdit,
    cast_ScriptEdit,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR
};
