/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.20
 */

#include "sipAPIqti.h"

#line 28 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 12 "../tmp/qtiplot/sipqtiQList0100QDateTime.cpp"

#line 397 "/usr/share/sip/PyQt4/QtCore/qdatetime.sip"
#include <qdatetime.h>
#line 16 "../tmp/qtiplot/sipqtiQList0100QDateTime.cpp"


extern "C" {static void assign_QList_0100QDateTime(void *, SIP_SSIZE_T, void *);}
static void assign_QList_0100QDateTime(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast<QList< ::QDateTime> *>(sipDst)[sipDstIdx] = *reinterpret_cast<QList< ::QDateTime> *>(sipSrc);
}


extern "C" {static void *array_QList_0100QDateTime(SIP_SSIZE_T);}
static void *array_QList_0100QDateTime(SIP_SSIZE_T sipNrElem)
{
    return new QList< ::QDateTime>[sipNrElem];
}


extern "C" {static void *copy_QList_0100QDateTime(const void *, SIP_SSIZE_T);}
static void *copy_QList_0100QDateTime(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QList< ::QDateTime>(reinterpret_cast<const QList< ::QDateTime> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QList_0100QDateTime(void *, int);}
static void release_QList_0100QDateTime(void *ptr, int)
{
    delete reinterpret_cast<QList< ::QDateTime> *>(ptr);
}



extern "C" {static int convertTo_QList_0100QDateTime(PyObject *, void **, int *, PyObject *);}
static int convertTo_QList_0100QDateTime(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QList< ::QDateTime> **sipCppPtr = reinterpret_cast<QList< ::QDateTime> **>(sipCppPtrV);

#line 59 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
    SIP_SSIZE_T len;

    // Check the type if that is all that is required.
    if (sipIsErr == NULL)
    {
        if (!PySequence_Check(sipPy) || (len = PySequence_Size(sipPy)) < 0)
            return 0;

        for (SIP_SSIZE_T i = 0; i < len; ++i)
        {
            PyObject *itm = PySequence_ITEM(sipPy, i);
            bool ok = (itm && sipCanConvertToType(itm, sipType_QDateTime, SIP_NOT_NONE));

            Py_XDECREF(itm);

            if (!ok)
                return 0;
        }

        return 1;
    }

    QList<QDateTime> *ql = new QList<QDateTime>;
    len = PySequence_Size(sipPy);
 
    for (SIP_SSIZE_T i = 0; i < len; ++i)
    {
        PyObject *itm = PySequence_ITEM(sipPy, i);
        int state;
        QDateTime *t = reinterpret_cast<QDateTime *>(sipConvertToType(itm, sipType_QDateTime, sipTransferObj, SIP_NOT_NONE, &state, sipIsErr));

        Py_DECREF(itm);
 
        if (*sipIsErr)
        {
            sipReleaseType(t, sipType_QDateTime, state);

            delete ql;
            return 0;
        }

        ql->append(*t);

        sipReleaseType(t, sipType_QDateTime, state);
    }
 
    *sipCppPtr = ql;
 
    return sipGetState(sipTransferObj);
#line 104 "../tmp/qtiplot/sipqtiQList0100QDateTime.cpp"
}


extern "C" {static PyObject *convertFrom_QList_0100QDateTime(void *, PyObject *);}
static PyObject *convertFrom_QList_0100QDateTime(void *sipCppV, PyObject *sipTransferObj)
{
   QList< ::QDateTime> *sipCpp = reinterpret_cast<QList< ::QDateTime> *>(sipCppV);

#line 32 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
    // Create the list.
    PyObject *l;

    if ((l = PyList_New(sipCpp->size())) == NULL)
        return NULL;

    // Set the list elements.
    for (int i = 0; i < sipCpp->size(); ++i)
    {
        QDateTime *t = new QDateTime(sipCpp->at(i));
        PyObject *tobj;

        if ((tobj = sipConvertFromNewType(t, sipType_QDateTime, sipTransferObj)) == NULL)
        {
            Py_DECREF(l);
            delete t;

            return NULL;
        }

        PyList_SET_ITEM(l, i, tobj);
    }

    return l;
#line 138 "../tmp/qtiplot/sipqtiQList0100QDateTime.cpp"
}


sipMappedTypeDef sipTypeDef_qti_QList_0100QDateTime = {
    {
        -1,
        SIP_NULLPTR,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_905,     /* QList<QDateTime> */
        {0},
        0
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_QList_0100QDateTime,
    array_QList_0100QDateTime,
    copy_QList_0100QDateTime,
    release_QList_0100QDateTime,
    convertTo_QList_0100QDateTime,
    convertFrom_QList_0100QDateTime
};
